services:
  dev:
    build:
      context: .
      target: dev
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    image: docugym-dev:latest
    container_name: docugym-dev
    hostname: docugym-dev
    security_opt:           #
      - seccomp=unconfined  #
    ipc: host               # These settings are okay to use in a local devcontainer
    volumes:
      - .:/app
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  runp:
    build:
      context: .
      target: run
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    image: docugym-run:latest
    container_name: docugym-run
    hostname: docugym-run
    volumes:
      - .:/app
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
